/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject82 {
    /// The plugin image to be uploaded
    #[serde(rename = "plugin")]
    pub plugin: std::path::PathBuf,
    /// Set to 'true' to overwrite a previously installed plugin with the same ID, if any
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<String>,
}

impl InlineObject82 {
    pub fn new(plugin: std::path::PathBuf) -> InlineObject82 {
        InlineObject82 {
            plugin,
            force: None,
        }
    }
}


