/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct BrandApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> BrandApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> BrandApiClient<C> {
        BrandApiClient {
            configuration,
        }
    }
}

pub trait BrandApi {
    fn brand_image_delete(&self, ) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>;
    fn brand_image_get(&self, ) -> Box<dyn Future<Output = Result<String, Error<serde_json::Value>>>>;
    fn brand_image_post(&self, image: std::path::PathBuf) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>;
}

impl<C: hyper::client::Connect>BrandApi for BrandApiClient<C> {
    fn brand_image_delete(&self, ) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Delete, "/brand/image".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;

        req.execute(self.configuration.borrow())
    }

    fn brand_image_get(&self, ) -> Box<dyn Future<Output = Result<String, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/brand/image".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;

        req.execute(self.configuration.borrow())
    }

    fn brand_image_post(&self, image: std::path::PathBuf) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/brand/image".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_form_param("image".to_string(), unimplemented!());

        req.execute(self.configuration.borrow())
    }

}
