/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct OAuthApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> OAuthApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> OAuthApiClient<C> {
        OAuthApiClient {
            configuration,
        }
    }
}

pub trait OAuthApi {
    fn oauth_apps_app_id_delete(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>;
    fn oauth_apps_app_id_get(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>;
    fn oauth_apps_app_id_info_get(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>;
    fn oauth_apps_app_id_put(&self, app_id: &str, inline_object81: crate::models::InlineObject81) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>;
    fn oauth_apps_app_id_regen_secret_post(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>;
    fn oauth_apps_get(&self, page: Option<i32>, per_page: Option<i32>) -> Box<dyn Future<Output = Result<Vec<crate::models::OAuthApp>, Error<serde_json::Value>>>>;
    fn oauth_apps_post(&self, inline_object80: crate::models::InlineObject80) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>;
    fn users_user_id_oauth_apps_authorized_get(&self, user_id: &str, page: Option<i32>, per_page: Option<i32>) -> Box<dyn Future<Output = Result<Vec<crate::models::OAuthApp>, Error<serde_json::Value>>>>;
}

impl<C: hyper::client::Connect>OAuthApi for OAuthApiClient<C> {
    fn oauth_apps_app_id_delete(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Delete, "/oauth/apps/{app_id}".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("app_id".to_string(), app_id.to_string());

        req.execute(self.configuration.borrow())
    }

    fn oauth_apps_app_id_get(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/oauth/apps/{app_id}".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("app_id".to_string(), app_id.to_string());

        req.execute(self.configuration.borrow())
    }

    fn oauth_apps_app_id_info_get(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/oauth/apps/{app_id}/info".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("app_id".to_string(), app_id.to_string());

        req.execute(self.configuration.borrow())
    }

    fn oauth_apps_app_id_put(&self, app_id: &str, inline_object81: crate::models::InlineObject81) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Put, "/oauth/apps/{app_id}".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("app_id".to_string(), app_id.to_string());
        req = req.with_body_param(inline_object81);

        req.execute(self.configuration.borrow())
    }

    fn oauth_apps_app_id_regen_secret_post(&self, app_id: &str) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/oauth/apps/{app_id}/regen_secret".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("app_id".to_string(), app_id.to_string());

        req.execute(self.configuration.borrow())
    }

    fn oauth_apps_get(&self, page: Option<i32>, per_page: Option<i32>) -> Box<dyn Future<Output = Result<Vec<crate::models::OAuthApp>, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/oauth/apps".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        if let Some(ref s) = page {
            req = req.with_query_param("page".to_string(), s.to_string());
        }
        if let Some(ref s) = per_page {
            req = req.with_query_param("per_page".to_string(), s.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    fn oauth_apps_post(&self, inline_object80: crate::models::InlineObject80) -> Box<dyn Future<Output = Result<crate::models::OAuthApp, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/oauth/apps".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_body_param(inline_object80);

        req.execute(self.configuration.borrow())
    }

    fn users_user_id_oauth_apps_authorized_get(&self, user_id: &str, page: Option<i32>, per_page: Option<i32>) -> Box<dyn Future<Output = Result<Vec<crate::models::OAuthApp>, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/users/{user_id}/oauth/apps/authorized".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        if let Some(ref s) = page {
            req = req.with_query_param("page".to_string(), s.to_string());
        }
        if let Some(ref s) = per_page {
            req = req.with_query_param("per_page".to_string(), s.to_string());
        }
        req = req.with_path_param("user_id".to_string(), user_id.to_string());

        req.execute(self.configuration.borrow())
    }

}
