/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct IntegrationActionsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> IntegrationActionsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> IntegrationActionsApiClient<C> {
        IntegrationActionsApiClient {
            configuration,
        }
    }
}

pub trait IntegrationActionsApi {
    fn actions_dialogs_open_post(&self, inline_object88: crate::models::InlineObject88) -> Box<dyn Future<Item = crate::models::StatusOk, Error = Error<serde_json::Value>>>;
    fn actions_dialogs_submit_post(&self, inline_object89: crate::models::InlineObject89) -> Box<dyn Future<Item = crate::models::StatusOk, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>IntegrationActionsApi for IntegrationActionsApiClient<C> {
    fn actions_dialogs_open_post(&self, inline_object88: crate::models::InlineObject88) -> Box<dyn Future<Item = crate::models::StatusOk, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/actions/dialogs/open".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_body_param(inline_object88);

        req.execute(self.configuration.borrow())
    }

    fn actions_dialogs_submit_post(&self, inline_object89: crate::models::InlineObject89) -> Box<dyn Future<Item = crate::models::StatusOk, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/actions/dialogs/submit".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_body_param(inline_object89);

        req.execute(self.configuration.borrow())
    }

}
