/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct LdapApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> LdapApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> LdapApiClient<C> {
        LdapApiClient {
            configuration,
        }
    }
}

pub trait LdapApi {
    fn ldap_groups_get(&self, q: Option<&str>, page: Option<i32>, per_page: Option<i32>) -> Box<dyn Future<Output = Result<Vec<crate::models::LdapGroupsPaged>, Error<serde_json::Value>>>>;
    fn ldap_groups_remote_id_link_post(&self, remote_id: &str) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>;
}

impl<C: hyper::client::Connect>LdapApi for LdapApiClient<C> {
    fn ldap_groups_get(&self, q: Option<&str>, page: Option<i32>, per_page: Option<i32>) -> Box<dyn Future<Output = Result<Vec<crate::models::LdapGroupsPaged>, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/ldap/groups".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        if let Some(ref s) = q {
            req = req.with_query_param("q".to_string(), s.to_string());
        }
        if let Some(ref s) = page {
            req = req.with_query_param("page".to_string(), s.to_string());
        }
        if let Some(ref s) = per_page {
            req = req.with_query_param("per_page".to_string(), s.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    fn ldap_groups_remote_id_link_post(&self, remote_id: &str) -> Box<dyn Future<Output = Result<crate::models::StatusOk, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/ldap/groups/{remote_id}/link".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("remote_id".to_string(), remote_id.to_string());

        req.execute(self.configuration.borrow())
    }

}
