/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct OpenGraphApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> OpenGraphApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> OpenGraphApiClient<C> {
        OpenGraphApiClient {
            configuration,
        }
    }
}

pub trait OpenGraphApi {
    fn opengraph_post(&self, inline_object87: crate::models::InlineObject87) -> Box<dyn Future<Output = Result<crate::models::OpenGraph, Error<serde_json::Value>>>>;
}

impl<C: hyper::client::Connect>OpenGraphApi for OpenGraphApiClient<C> {
    fn opengraph_post(&self, inline_object87: crate::models::InlineObject87) -> Box<dyn Future<Output = Result<crate::models::OpenGraph, Error<serde_json::Value>>>>{
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/opengraph".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_body_param(inline_object87);

        req.execute(self.configuration.borrow())
    }

}
