/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct StatusApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> StatusApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> StatusApiClient<C> {
        StatusApiClient {
            configuration,
        }
    }
}

pub trait StatusApi {
    fn users_status_ids_post(&self, request_body: Vec<String>) -> Box<dyn Future<Item = Vec<crate::models::Status>, Error = Error<serde_json::Value>>>;
    fn users_user_id_status_get(&self, user_id: &str) -> Box<dyn Future<Item = crate::models::Status, Error = Error<serde_json::Value>>>;
    fn users_user_id_status_put(&self, user_id: &str, inline_object25: crate::models::InlineObject25) -> Box<dyn Future<Item = crate::models::Status, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>StatusApi for StatusApiClient<C> {
    fn users_status_ids_post(&self, request_body: Vec<String>) -> Box<dyn Future<Item = Vec<crate::models::Status>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/users/status/ids".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_body_param(request_body);

        req.execute(self.configuration.borrow())
    }

    fn users_user_id_status_get(&self, user_id: &str) -> Box<dyn Future<Item = crate::models::Status, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/users/{user_id}/status".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("user_id".to_string(), user_id.to_string());

        req.execute(self.configuration.borrow())
    }

    fn users_user_id_status_put(&self, user_id: &str, inline_object25: crate::models::InlineObject25) -> Box<dyn Future<Item = crate::models::Status, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Put, "/users/{user_id}/status".to_string())
            .with_auth(__internal_request::Auth::Basic)
        ;
        req = req.with_path_param("user_id".to_string(), user_id.to_string());
        req = req.with_body_param(inline_object25);

        req.execute(self.configuration.borrow())
    }

}
